import Head from 'next/head';
// import Head from 'components/head';

import {useState} from 'react';
import Header from 'components/Header'
import Footer from 'components/Footer'

import Main from '/components/Main';


export default function Home() {

  const [locations, setLocations] = useState([])

  function locationCreateHandler(event) {
    event.preventDefault();
    const location = {
      name: event.target.locationName.value,
      minCustomers: event.target.minCustomers.value,
      maxCustomers: event.target.maxCustomers.value,
      avgCookies: event.target.avgCookiesPerSale.value,
      id: locations.length
    };
    setLocations([...locations, location])
  }
  
  return (
    <>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Main locationCreateHandler={locationCreateHandler} locations={locations}/>
      <Footer locations={locations}/>
    </>
  )
}
